services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tixxety
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/tixxety
      SYNC_DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/tixxety
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      TICKET_RESERVATION_TTL_SECONDS: 120
    ports:
      - '8000:8000'
    command: ['uvicorn', 'app.main:app', '--host', '0.0.0.0', '--port', '8000']

  worker:
    build: .
    depends_on:
      - api
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/tixxety
      SYNC_DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/tixxety
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      TICKET_RESERVATION_TTL_SECONDS: 120
    command:
      ['celery', '-A', 'app.celery_app.celery_app', 'worker', '--loglevel=INFO']

  beat:
    build: .
    depends_on:
      - worker
      - redis
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/tixxety
      SYNC_DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/tixxety
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    command:
      ['celery', '-A', 'app.celery_app.celery_app', 'beat', '--loglevel=INFO']

volumes: {}
